[project]
name = "promoe"
version = "0.1.0"
description = "PromoE using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.118.0,<1.0.0"
]

[project.scripts]
promoe = "promoe.main:run"
run_crew = "promoe.main:run"
train = "promoe.main:train"
replay = "promoe.main:replay"
test = "promoe.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
